# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Niloofar Borhani
email: n.borhani@ec.iut.ac.ir
phone: (+98)9133203525
cv   : "resume.pdf"
website: https://scholar.google.com/citations?user=SSD_k8MAAAAJ&hl=en&oi=ao

# Social links
#twitter_username: jekyllrb
#github_username:  moya10
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: niloofar-borhani-594005189
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)    While working on biological systems, their networks and behavior, I was always fascinated by how “engineered” those systems are. As a control engineer, I was trained to implement control algorithms and yet I could detect “finely-tuned control modules” which were right there at the heart of biological networks. 

about_profile_image: images/ax.png
about_content: | # this will include new lines to allow paragraphs [PDF Of My Resume](https://moya10.github.io/awesome-cv/resume.pdf) 
 
 
 
 **Research Interest:**
   - Machine Learning, Deep Learning
   - Network Embedding
   - Representation Learning
   - Data Science
   - Systems Biology
   - Systems Modeling
   
   
  **Important Related Courses:**
   - Deep Learning
   - Artificial Neural Network
   - Biology (in Isfahan university of Medical Sciences)
   - System Identification
   - Dynamic Systems
   - Stochastic Process
   - Nonlinear Control   
   
# Education Section
# education_title: Education #(Use this to override about education section title)
#I received my B.Sc. and M.Sc. degrees with honors in Electrical Engineering (Control engineering) from Isfahan University of Technology (IUT), Iran, in 2020 and 2017 respectively. My graduate studies were mostly focused on the systems biology and therefore, I used to work simultaneously at "Department of electrical and computer engineering (Isfahan university of technology)" and "Regenerative Medicine Research Center (Isfahan University of Medical Sciences)" to be able to apply modeling approaches especially deep learning methods with hot topics in biology.   
#During my master's program, I became interested in systems biology. My M.Sc. thesis was about predicting inter-omics interactions in multi-layer networks by deep learning methods. As a control engineer, I was trained to identify and model systems in order to predict their responses and then implement control algorithms. While working on biological systems, I was always fascinated by how these engineered methods are suitable and helpful for biological systems and blending machine learning, statistics and data science in biology can bring novel biomedical insights.  That makes me enthusiastic to pursue a Ph.D. in the same field. The Dissertation will be about predicting the druggability of protein by machine learning methods. This can facilitate target discovery in drug development.


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Dr. Iman Izadi**, Associative Professor, Department of Electrical and Computer Engineering, Isfahan University of Technology, Isfahan, Iran, *iman.izadi@iut.ac.ir* 
  
  **Dr. Yousof Gheisari**, MD, PhD, Associative Professor, Isfahan University of Medical Sciences, Isfahan, Iran, *ygheisari@med.mui.ac.ir*
  
  **Dr. Jafar Ghaisari**, Associative Professor, Department of Electrical and Computer Engineering, Isfahan University of Technology, Isfahan, Iran, *ghaisari@cc.iut.ac.ir* 
  
  **Dr. Marzieh Kamali**, Assistant Professor, Department of Electrical and Computer Engineering, Isfahan University of Technology, Isfahan, Iran, *m.kamali@cc.iut.ac.ir* 

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
