# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Niloofar Borhani
email: borhaniniloofar1374@gmail.com
phone: (+98)9133203525
cv   : "resume.pdf"
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
#github_username:  moya10
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: niloofar-borhani-594005189
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/ax.png
about_content: | # this will include new lines to allow paragraphs [PDF Of My Resume](https://moya10.github.io/awesome-cv/resume.pdf) 
 I received my B.Sc. and M.Sc. degrees with honors in Electrical Engineering (Control engineering) from Isfahan University of Technology (IUT), Iran, in 2020 and 2017 respectively. My graduate studies were mostly focused on the interdisciplinary field of systems biology and therefore, I used to work simultaneously at "Department of electrical and computer engineering (Isfahan university of technology)" and "Regenerative Medicine Research Center (Isfahan University of Medical Sciences)" to be able to integrate modeling approaches with hot topics in biology. 
 
 
 I started to get interested in systems biology when I was working on my M.Sc. thesis which was about predicting inter-omics interactions in multi-layer networks by deep learning methods. While working on biological systems, their networks and modules, I was always fascinated by how “engineered” those systems are. As a control engineer, I was trained to implement control algorithms and yet I could detect “finely-tuned control modules” which were right there at the heart of biological networks. That fascination led me to persue a Ph.D. in the same field. The Dissertation was centered around revealing the dynamics behind macrophage polarization and phenotype distribution using mathematical modeling approaches. 

 
 **Research interest:**
   - Machine learning, Deep learning
   - Network embedding
   - Representation learning
   - Data science
   - Systems biology
   - Systems modeling
    
# Education Section
# education_title: Education #(Use this to override about education section title)

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Dr. Iman Izadi**, Associative Professor, Department of Electrical and Computer Engineering, Isfahan University of Technology, Isfahan, Iran, *iman.izadi@iut.ac.ir* 
  
  **Dr. Yousof Gheisari**, MD, PhD, Associative Professor, Isfahan University of Medical Sciences, Isfahan, Iran, *ygheisari@med.mui.ac.ir*
  
  **Dr. Jafar Ghaisari**, Associative Professor, Department of Electrical and Computer Engineering, Isfahan University of Technology, Isfahan, Iran, *ghaisari@cc.iut.ac.ir* 
  
  **Dr. Marzieh Kamali**, Assistant Professor, Department of Electrical and Computer Engineering, Isfahan University of Technology, Isfahan, Iran, *m.kamali@cc.iut.ac.ir* 

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
